apiVersion: v1
kind: Pod
metadata:
  name: flask-application
  labels:
    app: flask
spec:
  containers:
  - name: flask-app
    image: nischalchudal/flask:1.2
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: docker-secrets
