FROM nginx:latest

WORKDIR /home

# Copy the current directory contents into the container at /home
# Copying the static files to the nginx html directory
COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80
# The default command to run when the container starts

CMD [ "COPY" ]



